# Generated by Django 4.1 on 2023-05-07 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='cuisine',
            new_name='country',
        ),
    ]
