# Generated by Django 4.1 on 2023-05-07 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0004_menucategories_menu_category_id'),
    ]

   