# Generated by Django 4.1 on 2023-05-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0005_remove_menucategories_menu_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategories',
            name='menu_category_name',
            field=models.CharField(default='default_category', max_length=200),
        ),
    ]
