# Generated by Django 4.2.1 on 2023-05-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0011_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='phone_number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
