# Generated by Django 4.2.1 on 2023-05-30 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0012_alter_registration_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logger',
            name='time_log',
        ),
        migrations.AddField(
            model_name='logger',
            name='booking_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
